### ISSUE TITLE
Redirect not working as expected.

### ISSUE THREAD

**Issue by LongDirtyAnimAlf** [synopse/mORMot2#42]
To reproduce: use wget function to ty to download a file that has redirects.
> https://download.opensuse.org/distribution/leap/15.3/iso/openSUSE-Leap-15.3-NET-x86_64-Current.iso

This triggers the redirect functionality in function THttpClientSocket.Request.
This redirect receives the location header:
ctxt.url := HeaderGetValue('LOCATION'); // internal redirection only
This new url can be on a new server, with a new port, even a new file.
So, a whole new connection may be needed to follow the redirect.
At this moment, the current connection is used that can only work with a changed address part on the same remote server.

I guess a new connection is needed with the new LOCATION-url and all other settings that are needed for this new url.

**Comment by synopse** [comment]
I have committed redirection to any other server.

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the quick fix ! The redirect is working. But not 100% yet !
Try to download this file with mORMot wget:
https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.2/WinCrossBinsAppleAll.zip
You will get an error when trying to unzip this file. This is due to the fact that the redirect response by the server is included in the downloaded zip.


![Capture](https://user-images.githubusercontent.com/10783972/127855694-8876ec1c-1cd6-4a31-b25f-0c6f09bb5635.PNG)

**Comment by synopse** [comment]
I am not able to reproduce it.
Are you using a stream?

**Comment by synopse** [comment]
Hope it is as you expect now.

**Comment by LongDirtyAnimAlf** [comment]
Mmmmm ... still not working on my side !
I am on Windows10, AMD64.
Simple form with a single button and this code:
```
uses
  mormot.net.client;

procedure TForm1.Button1Click(Sender: TObject);
const
  ZIPPED='zipped.zip';
var
  params: THttpClientSocketWGet;
begin
  params.Clear;
  params.Resume := true;
  if params.WGet('https://github.com/LongDirtyAnimAlf/fpcupdeluxe/releases/download/wincrossbins_v1.2/WinCrossBinsAppleAll.zip',ZIPPED,
       '', nil, 5000, 5) <> ZIPPED then
  begin
  end;
end;

```

**Comment by synopse** [comment]
It seems now fixed on my side...

**Comment by LongDirtyAnimAlf** [comment]
Working perfect now !
Thanks again for the quick fix !!

**Comment by synopse** [comment]
I guess you could use this WGet for fpcupdeluxe, especially with the   `params.OnProgress := TStreamRedirect.ProgressToConsole;` option.
It has been well tested on Windows (using the SChannel TLS layer) and on Linux (using OpenSSL). It should work with other POSIX and OpenSSL. But HTTPS is likely not to work on MacOS if there is no OpenSSL available...

**Comment by LongDirtyAnimAlf** [comment]
> I guess you could use this WGet for fpcupdeluxe,

Yes, that was the main reason for me to try to download files with your wget ! Its very hard to get downloads working on all systems.
There remain two problems: (very) old OSX and (very) old Windows.
For now, I have enabled the mORMot wget for the GUI frontend when downloading cross-tools on Windows and Linux.
Will dive a bit deeper to see if wget can be used for (non-svn and non-git) sources and system-binaries also.

**Comment by synopse** [comment]
I have just tested that if you use OpenSLL 1.1 libraries on Windows, it works even on Windows XP.
The mormot.lib.openssl11.pas unit first load the dll from the executable folder, so it may help to avoid troubles with unexpected libraries in the path or anywhere else.

**Comment by synopse** [comment]
Here are my working Open SSL 1.1 dll for Windows XP and up.
[OpenSSL11Win32.zip](https://github.com/synopse/mORMot2/files/6919402/OpenSSL11Win32.zip)

**Comment by LongDirtyAnimAlf** [comment]
Thanks for the files. They are working !
However. Its a (well known) chicken and the egg problem. Fpcupdeluxe has to download these files to be able to use them. And it needs to setup a https connection to download. Which fails without these files.
Will think about something ! Perhaps a dedicated zip-file for XP that contains fpcupdeluxe and these files.

**Comment by LongDirtyAnimAlf** [comment]
Re-opening due to a related small issue.
With the current code, downloading zip-files from Github fails. This is due to the fact that Github does not accept the mORMot user agent.
As the current implementation is called wget, I propose to use wget also as user agent. This will be accepted by github.

File to try to dowload:
'https://github.com/graemeg/freepascal/archive/master.zip'

```
    s.RedirectMax := redirectmax;
    s.UserAgent:='Wget/1.20.3'; //<----------------------------- needed for success !!
    result := s.WGet(u, destfile, self);

```

**Comment by LongDirtyAnimAlf** [comment]
Bugger. Additional.
The issue is real. Settings the user-agent does not solve [yet].
Will look further. Sorry about this.

**Comment by LongDirtyAnimAlf** [comment]
Closing again. The reported problem with the Github zip-file cannot be reproduced by me.
Will open again when needed. Sorry for the noise.

**Comment by synopse** [comment]
Or you could embed the dll inside a zip inside an executable resource. mormot.core.zip allows this directly.
